name: Carga Codigo A carpeta S3

on: 
    push:
      branches:
      - Code_tested

#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@master
#    - uses: jakejarvis/s3-sync-action@master
#      with:
#        args: --acl public-read --follow-symlinks --delete --exclude *.git*/*
#      env: 

jobs:
  approve-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # This step would be skipped unless PR is approved and merged
    - name: Deploy to S3
      if: github.event.pull_request.merged == true
      run: |
        aws s3 sync . s3://prueba-carga-codigo/test1-codeoncarpet-s3/ --delete
      env:      
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ 'pBKh9dnw9CCiMiLaS+iNX9lF2ivgdjBRiVtebN8V' }}